variables:
  asocApiKeyId: 'cce45239-2615-6dc8-7713-df1f2f1f3f3f'
  asocApiKeySecret: 'pxuohn7vVd5dq4Q+VJIGulgsQsz2x0BZtVlKgQ3BJu7Y'
  asocAppName: $CI_PROJECT_NAME
  serviceUrl: 'cloud.appscan.com'
  assetGroupId: '9083a7ce-a9c6-46b9-8162-d6385c7741c6'
  scanName: $CI_PROJECT_NAME-$CI_JOB_ID
  sevSecGw: 'criticalIssues'
  maxIssuesAllowed: 100


include:
  - remote: 'https://raw.githubusercontent.com/jrocia/Integration-ASoC-and-Gitlab/main/yaml/appscanasoc_scan_sast.yaml'

stages:
- scan-sast

scan-job:
  stage: scan-sast